/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    DataSourceSwitch: typeof import('./src/components/common/DataSourceSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorMessage: typeof import('./src/components/common/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    PriceTag: typeof import('./src/components/stock/PriceTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
    StockCard: typeof import('./src/components/stock/StockCard.vue')['default']
    StockDetail: typeof import('./src/components/stock/StockDetail.vue')['default']
    StockGrid: typeof import('./src/components/stock/StockGrid.vue')['default']
    StockList: typeof import('./src/components/StockList.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
  }
}
